### PR TITLE
Create documentation-style-guide

### PR DESCRIPTION
**Pull request by diana-lakatos**
I started the documentation style guide with the generic writing guidelines and the guidelines for writing quickstart guides. We will continuously update it as we work on the documentation and the different documentation content types.

### CODE REVIEW

**Comment by pavelloz** [comment]
Good job :)

I don't know if anybody shared this, but might be helpful (tables, code highlighting, raw - those three were tricky, because markdown can be tricky to use when trying to document code and/or arguments/available options, default values etc.) - http://documentation.near-me.com/contributing

BTW. I think headings in markdown (at least in github) require space between # and the text


##test
## test

**Comment by diana-lakatos** [comment]
Thank you for your feedback and for pointing me to content I could reuse. I edited the content, please see the list of changes in the commit message (please tell me if you'd rather like to see the list of changes in my comment or both). 

I imagine we will have two pages:
- One with the general contribution information (currently https://github.com/mdyd-dev/nearme-documentation/blob/master/pages/contributing.md)
- The style guide with all the writing and formatting related information
What do you think? 

What I could still add, but would need some more info on: 
- how contributors can upload and insert images
- what formatting contributors should use instead of screenshots for the Form configuration view

Thanks!

**Comment by pavelloz** [comment]
1. Yes, I also think one document should be "formatting" oriented, second one how to actually do it step by step if i wanted to contribute as an channel partner.

2. 
a) since we are going to use our own platform we will decide how to handle images, building it gives us 100% flexibility - probably we will use something like https://uppy.io/ embedded into "Create/Edit post" page - those images will be either assigned to the user, article, or maybe someone will have even better idea, how to have a screenshot that can be reused in many places (dont know if thats something useful or not, just brainstorming here)

b) can you give an example of whats form configuration view? all the formats (syntaxes) that we use in our system are supported (and hopefully will be supported still, after we migrate to our platform) the highlighting engine we are using, so liquid, yaml, graphql, html - everything can be wrapped into code blocks if thats not too verbose/long.

Example form configurations/yaml+liquid combination:
http://documentation.near-me.com/reference/form-configurations-static/
http://documentation.near-me.com/reference/authorization-policy/maciej

**Comment by pavelloz** [comment]
PS. Having changes in commits is 100% fine, its how we do things everywhere else anyway, so we are used to reading diffs :)

**Comment by diana-lakatos** [comment]
Thank you for your detailed feedback!

As we've discussed, form configuration is just another type of definition from the developer perspective, so I updated the formatting of form configuration view according to this. 

We'll keep an eye on the image insert, and update the docs once we have a solution for it.

**Comment by Developer-DNM** [comment]
Can we also account for embedding video content:

`<iframe width="560" height="315" src="https://www.youtube.com/embed/cKbaP-8-VFE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>`

And the cool tool Pawel has found: https://asciinema.org/ 

[asciicast](https://asciinema.org/a/NVnmfa2SExykHRjKzmI9uWpHY)

**Comment by diana-lakatos** [comment]
Thank you! 
I updated the style guide based on your feedback, added a section about embedding videos.

**Pull request merged**
